### ISSUE TITLE
Dodatkowy kondensator 100uF na linii 6V

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#11]
Trzeba dodać kondensator 100nF (z DS) do pinu VM

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/8cd587369a88bf1a04ddcbafc6c34fccc7df5dc4)

**Comment by bartek1333** [comment]
In DS example is 0.1uF ceramic, not 100uF

**Comment by mrozsebastian** [comment]
Na przykładowym układzie nie ma nic o 0.1uF na VM. 0.1uF nic nie da na wejściu mostka, za duże prądy przepływają. Można pomyśleć nad jakimiś kondensatorami na pinach silników. ![image](https://user-images.githubusercontent.com/15183460/76159809-57eba780-6124-11ea-8088-c8973b919a11.png)

**Comment by bartek1333** [comment]
Nie wiem co to jest za przykładowy schemat, ale ten poniżej jest z DS:
![mostek](https://user-images.githubusercontent.com/38117891/76164628-bb8bca00-6150-11ea-9df5-ed6ca5c0733d.PNG)

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/1e9b78f6cea6090ee7997e9f168c55b7f5af0730)
