### ISSUE TITLE
Połączenie z czujnikiem XSHUT

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#12]
W sumie o tym już gadaliśmy, ale napisze. Procek powinien na spokojnie sterować pinem xshut nawet jeśli jest podłączony do 2.8V (zwierać do masy w trybie open drain).
Odpada wtedy 1 rezystor i 2 napięcia koło siebie na jednej linii

**Comment by mrozsebastian** [comment]
DS do VC53L0x zaleca napięcie 2.8 i napięcie na pinach XSHUT powinno być takie jak zasilające. Poza tym można pominąć wlutowanie rezystorów i zastąpić je 0R i wyjdzie na to samo.

**Comment by bartek1333** [comment]
Który rezystor chcesz zastąpić przez 0R że wyjdzie to samo?
Jak będzie open drain i rezystor do 2.8V, to będzie zgodnie z DS, 0-2.8

**Comment by mrozsebastian** [comment]
Zwarcie padów dwóch rezystorów. Da się wykonać w obecnym układnie

**Comment by bartek1333** [comment]
Tak czy inaczej, będzie to trzeba sterować z open drain, a nie push-pull, bo na xshut pójdzie 3.3. Więc po co kombinować z dwoma napięciami i zworkami ewentualnymi

**Comment by mrozsebastian** [comment]
Wontfix

**Comment by bartek1333** [comment]
Sam napisałeś że tam ma być 2.8V.
Sprawdź w symulacji, że tam wyjdzie 3.3

**Comment by mrozsebastian** [comment]
Wciąż, da się wykonać na aktualnym schemacie, przykładowo R38 0R albo zwora. Ten układ jest w dokumentacji do modułów Polulu z którymi Arduino 5V czy Nucleo 3V3 bez problemu się komunikują.
 
![image](https://user-images.githubusercontent.com/15183460/76153990-f94b0d00-60d4-11ea-8ae1-da68b2343cb1.png)

![image](https://user-images.githubusercontent.com/15183460/76153997-1a136280-60d5-11ea-9473-14edc72eb097.png)

**Comment by bartek1333** [comment]
Co Ci da zastąpienie R38 zworą czy 0R?

Cytat ze strony https://www.pololu.com/product/2490 

The XSHUT pin is an input and the GPIO1 pin is an open-drain output; both pins are pulled up to 2.8 V by the board. They are not connected to level-shifters on the board and are not 5V-tolerant, but they are usable as-is with many 3.3 V and 5 V microcontrollers: the microcontroller can read the GPIO1 output as long as its logic high threshold is below 2.8 V, and the microcontroller can alternate its own output between low and high-impedance states to drive the XSHUT pin. Alternatively, our 4-channel bidirectional logic level shifter can be used externally with those pins.

Więc komunikują się z nim procki 3.3V i 5V tylko dlatego, że ma wbudowany na liniach I2C logic level shifter. Natomiast już sterowanie pinem XSHOUT nie jest takie proste bo na płytce (i na naszym schemacie) nie ma konwertera napięć. I jedyne co procek może zrobić to zwierać do GND lub wisieć w powietrzu, żeby nie dać 3.3 lub 5V na układ.
Dlatego to 3.3V tam nie powinno być, bo w symulacji wychodzi, że na XSHOUT będzie szło 3.3V gdy na wyjściu procka będzie logiczne 1 (push pull). Przy open drain bez ściągania do masy, też na xshout będzie ponad 3V.

Dlatego to 3.3V trzeba usunąć. Procki o których pisałeś komunikują się z tym, nie wystawiając 1-0 na linie, tylko zwierając albo do masy, albo float.

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/1e9b78f6cea6090ee7997e9f168c55b7f5af0730)
