### ISSUE TITLE
Rezystory przy switchach - opcjonalne

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#15]
Czytałem, że dobrym sposobem obsługi przycisków jest dawanie rezystorów pomiędzy nimi a masą. Bo kondensator się szybko rozładowuje jak klikniesz, duży prąd idzie do masy. Styki się wyrabiają, może inne wady też są

**Comment by mrozsebastian** [comment]
Którędy płynie duży prąd? Jedynie gdzie może popłynąć to przez rezystor 10K

**Comment by bartek1333** [comment]
od kondensatora do masy, dlatego styki się mogą psuć. No i duży prąd wtedy płynie. Chwilowy, bo chwilowy ale duży
