### ISSUE TITLE
Usunąć pull up przy enkoderach

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#16]
model A ma wyjścia push-pull, więc pull upy 10k do 5V nie są potrzebne

**Comment by mrozsebastian** [comment]
Wyjścia są programowalne, mogą być też open-drain. Można też po prostu nie lutować tych rezystorów

**Comment by bartek1333** [comment]
Też widzę w DS, że są programowalne. Ale to jest chyba kit. Jedyne co znalazłem to:
Both chips are available with push-pull
outputs (AS530xA) or with open drain outputs (AS530xB).

Ale jak mówisz, można nie lutować rezystorów

**Comment by bartek1333** [comment]
Jakiś komentarz? :)
