### ISSUE TITLE
Przycisk resetu

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#19]
Nie mogę zlokalizować przycisku resetu. Jeśli go nie ma, to dobrze mieć reset myszki pod ręką

**Comment by mrozsebastian** [comment]
![image](https://user-images.githubusercontent.com/15183460/76361098-8d5be500-631e-11ea-9bc7-03c9248405cf.png)

🙃

**Comment by bartek1333** [comment]
xD
