### ISSUE TITLE
pull up I2C

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#4]
Pull-Up dla 3.3V ok 2k7, nie 10k. Nad 2.8V trzeba rozkminić

**Comment by mrozsebastian** [comment]
2K7 będzie dobre też dla 2.8V a nie dodajemy kolejnej wielkości rezystora do BOM

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/8cd587369a88bf1a04ddcbafc6c34fccc7df5dc4)
