### ISSUE TITLE
rezystor przy kwarcu stm32 OSC_OUT

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#5]
Często na schematach jest rezystor na OSC_OUT. Można wstawić miejsce. Jak nie będzie potrzebny, wtedy zworka

**Comment by mrozsebastian** [comment]
Są tam dawane 0R albo robione zworki, nie zmienia nic w schemacie.

![image](https://user-images.githubusercontent.com/15183460/76153753-d9b1e580-60d0-11ea-9e45-df9d61209f5f.png)
