### ISSUE TITLE
Odwrócić diodę zasilania na schemacie, by włączała się po załączeniu zasilania

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#7]
Może warto dodać diodę, odwrotnie spolaryzowaną niż ta czerwona przy zasilaniu?
Żeby dobre zasilanie też było sygnalizowane

**Comment by mrozsebastian** [comment]
Nie warto, będzie pobierać prąd nawet przy wyłączonym zasilaniu dla całej myszki. Dioda od zasilania jest wystarczająca. Jeżeli po włączeniu robota nie zapali się to wystarczający sygnał, że jest coś nie tak

**Comment by bartek1333** [comment]
"Dioda od zasilania jest wystarczająca. Jeżeli po włączeniu robota nie zapali się to wystarczający sygnał, że jest coś nie tak"
O której diodzie mówisz? Widzę tylko tą czerwoną, która się zapala jeśli jest coś nie tak

**Comment by bartek1333** [comment]
Nie czaje zmiany tytułu. Ta czerwona ma się świecić chyba jak jest podłączone źle.
Mi chodziło o diodę, która sygnalizuje że jest podłączone dobrze, bo takiej nie widziałem. Ale fakt, po co się ma świecić jak tylko lipola się włączy, może za włącznikiem ją wstawić?

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/8cd587369a88bf1a04ddcbafc6c34fccc7df5dc4)
