### ISSUE TITLE
zmiana wartości rezystora przy LM1117 6V

### ISSUE THREAD

**Issue by bartek1333** [synergia/synermycha-electronics#8]
Policzyłem i bliższą wartością dla 6V na wyjściu, będzie wstawienie zamiast 3k16, to 3k32 z szeregu E192 (0.5%)

**Comment by mrozsebastian** [comment]
Fixed in [commit](https://github.com/synergia/synermycha-electronics/commit/8cd587369a88bf1a04ddcbafc6c34fccc7df5dc4)
